### PR TITLE
Remove unnecessary iteration in `validate_memory_cell`

### PR DESCRIPTION
**Pull request by fmoletta**
# TITLE

## Description

Description of the pull request changes and motivation.

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by Oppen — APPROVED** [review]
Great catch! I'd like to compare the benchmarks, I expect at least a few percent improvement.

**Comment by Oppen** [comment]
Oddly enough there seems to be a small hit. I suspect there's something wrong with the workflows tho.

**Comment by fmoletta** [comment]
> Great catch! I'd like to compare the benchmarks, I expect at least a few percent improvement.

The lenght of the validation rules will always be bewteen 0 and 2 (due to the existinng builtins), so there wont be a noticeable performace gain

**Comment by Oppen** [comment]
> The length of the validation rules will always be bewteen 0 and 2 (due to the existinng builtins), so there wont be a noticeable performace gain

Right. I thought it was iterating over segments.

**Review by Jrigada — APPROVED** [review]

**Pull request merged**
