### PR TITLE
add deserialize program from string

### PR DESCRIPTION
**Pull request by raefko**
# add deserialize program from string

## Description

Add a function to deserialize a program from a string. We ([FuzzingLabs](https://github.com/FuzzingLabs)) need it for the fuzzer so it to optimize the I/O of the fuzzer

## Checklist
- [ ] Linked to Github Issue
- [x] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Comment by Oppen** [comment]
This doesn't seem necessary. Slices implement `Read`, so you can just call `.as_bytes()` on the string and pass the result to the existing function. If you're more comfortable using a helper it may be acceptable, but please make it just a thin wrapper that pass `.as_bytes()`.

**Comment by Oppen** [comment]
@raefko any news about this? Is the solution I proposed good enough or do we need to keep working on this?

**Comment by raefko** [comment]
We benchmarked your solution, and our solution is faster (which is essential for fuzzing)

> This doesn't seem necessary. Slices implement `Read`, so you can just call `.as_bytes()` on the string and pass the result to the existing function. If you're more comfortable using a helper it may be acceptable, but please make it just a thin wrapper that pass `.as_bytes()`.

**Comment by Oppen** [comment]
Have you tried preallocating with a bigger capacity?

**Comment by Oppen** [comment]
Questions:
1. How much faster?
2. How was this benchmarked?
3. Where does the bottleneck lie in each case?

**Comment by Oppen** [comment]
So, I double checked the changes and both functions differ only on the serde call. Let's extract that so we don't copy paste the whole thing.

**Comment by Oppen** [comment]
Currently the VM reads the whole program and deserializes from a slice of bytes. This should also work for this use case, so I'm closing the PR. We can open it again if you have any objections.

**Pull request closed without merging**
