### PR TITLE
cairo programs v0.10.x compatible

### PR DESCRIPTION
**Pull request by oxlime**
#417 

cairo-migrate for all cairo files

### CODE REVIEW

**Comment by Juan-M-V** [comment]
Hi @oxlime!
Thank you so much for your contribution, I'm reviewing your PR, it looks good so far but I want to run tests locally before approving it. To do that, I have to update some of the hint that the common library uses. I'll get back to you as soon as I do that!

**Comment by Juan-M-V** [comment]
Hi @oxlime,
I sent you a PR with the needed changes to pass the tests and merge your contribution. Thank you for your interest in our project!

**Comment by oxlime** [comment]
Awesome thx for the help Juan!

**Review by Juan-M-V — APPROVED** [review]
Awesome work! I'll merge your PR as soon as we get another approval

**Review by entropidelic — CHANGES_REQUESTED** [review]
Hi @oxlime, thank you very much for your contribution! Just a little detail, the Makefile should be changed to use the new cairo version. More specifically, the deps phony target. Once that is done, this should be ready to merge :)

**Comment by Oppen** [comment]
Closing this because it got stale and it was covered by a different PR in the meantime.

**Pull request closed without merging**
