### PR TITLE
Add property testing for Felt bit shifts

### PR DESCRIPTION
**Pull request by martinacantaro**
# Add property testing for Felt bit shifts

## Description

Property-based test that ensures, for 100 `value`s that are randomly generated each time tests are run, that performing a bit shift to the left or to the right by `shift_amount` of bits (between 0 and 999) returns a result that is inside of the range [0, p].

## Checklist
- [x] Linked to Github Issue https://github.com/lambdaclass/cairo-rs/issues/700
- [x] Unit tests added
- [-] Integration tests added.
- [-] This change requires new documentation.
  - [-] Documentation has been added/updated.

### CODE REVIEW

**Comment by igaray** [comment]
Tests look good! but one thing I see consistently missing is comments on tests indicating motivation, *what* the tests wants to check, and not *how* it does it. This improves both understanding for newcomers,  modification of the tests in the future, and most importantly, debugging when someone else makes them fail. 
The PR description could be expanded and included in the corresponding tests.

**Comment by martinacantaro** [comment]
Added comments to each test. 

Please don't merge because I also want to check if a particular change to the tests is needed

**Comment by martinacantaro** [comment]
All done! The change wasn't necessary

**Review by Juan-M-V — APPROVED** [review]
Great work!

**Review by Oppen — APPROVED** [review]

**Pull request merged**
