### PR TITLE
use get_prime method

### PR DESCRIPTION
**Pull request by Juan-M-V**
# TITLE

## Description

Partially apply vm_proxy.get_prime(). Leave out memory.write_arg instances

## Checklist
- [ ] Linked to Github Issue
- [ ] Unit tests added
- [ ] Integration tests added.
- [ ] This change requires new documentation.
  - [ ] Documentation has been added/updated.

### CODE REVIEW

**Review by fmoletta — COMMENTED** [review]
Is it possible to make the prime field in VMProxy private with these changes?

**Review by pefontana — CHANGES_REQUESTED** [review]
@Juan-M-V you can leave the `vm_proxy.prime` of the functions used in `vm_proxy.memory.write_ar`g because it will be deleted #455
But there are still some other vm_proxy.prime around the code, for example in: `src/hint_processor/builtin_hint_processor/cairo_keccak/keccak_hints.rs`. Please check them.

**Comment by pefontana** [comment]
> Is it possible to make the prime field in VMProxy private with these changes?

@fmoletta Once #455 is merged we will be able to pass VMProxy.prime as a private field

**Comment by Juan-M-V** [comment]
> @Juan-M-V you can leave the `vm_proxy.prime` of the functions used in `vm_proxy.memory.write_ar`g because it will be deleted #455 But there are still some other vm_proxy.prime around the code, for example in: `src/hint_processor/builtin_hint_processor/cairo_keccak/keccak_hints.rs`. Please check them.

Resolved: https://github.com/lambdaclass/cairo-rs/pull/460/commits/bdd527804e160cc10bf03808febd120a1427d0fe

**Review by pefontana — APPROVED** [review]

**Review by Oppen — APPROVED** [review]

**Pull request merged**
